customhost = "project2db.ctbdyegtjbsz.us-east-1.rds.amazonaws.com"
customuser = "admin"
custompass = "admin1234"
customdb = "project2db"
custombucket = "my-project2-bucket"
customregion = "us-east-1"
