customhost = "project2db.ctbdyegtjbsz.us-east-1.rds.amazonaws.com"
customuser = "admin"
custompass = "admin1234"
customdb = "project2db"
custombucket = "nishabuck"
customregion = "US East (N. Virginia) us-east-1"
